import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
    children: React.ReactNode;
  }>) {
  return (
    <html lang="en">
      <body className="w-screen h-screen bg-black flex flex-col">
        <header className="bg-gray-950 m-3">
          <p className="text-white">Header</p>
        </header>
        {children}
        <footer className="bg-gray-950 m-3">
          <p className="text-white">Footer</p>
        </footer>
      </body>
    </html>
  );
}
